/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedQuotesRouteImport } from './routes/_authenticated/quotes'
import { Route as AuthenticatedProductsRouteImport } from './routes/_authenticated/products'
import { Route as AuthenticatedPriceListsRouteImport } from './routes/_authenticated/price-lists'
import { Route as AuthenticatedPagesRouteImport } from './routes/_authenticated/pages'
import { Route as AuthenticatedOrdersRouteImport } from './routes/_authenticated/orders'
import { Route as AuthenticatedMediaRouteImport } from './routes/_authenticated/media'
import { Route as AuthenticatedInvoicesRouteImport } from './routes/_authenticated/invoices'
import { Route as AuthenticatedInventoryRouteImport } from './routes/_authenticated/inventory'
import { Route as AuthenticatedGiftCardsRouteImport } from './routes/_authenticated/gift-cards'
import { Route as AuthenticatedDiscountsRouteImport } from './routes/_authenticated/discounts'
import { Route as AuthenticatedCustomersRouteImport } from './routes/_authenticated/customers'
import { Route as AuthenticatedCompaniesRouteImport } from './routes/_authenticated/companies'
import { Route as AuthenticatedCollectionsRouteImport } from './routes/_authenticated/collections'
import { Route as AuthenticatedBlogsRouteImport } from './routes/_authenticated/blogs'
import { Route as AuthenticatedProductsIndexRouteImport } from './routes/_authenticated/products.index'
import { Route as AuthenticatedSettingsShippingRouteImport } from './routes/_authenticated/settings/shipping'
import { Route as AuthenticatedSettingsPermissionsRouteImport } from './routes/_authenticated/settings/permissions'
import { Route as AuthenticatedSettingsLocationsRouteImport } from './routes/_authenticated/settings/locations'
import { Route as AuthenticatedQuotesQuoteIdRouteImport } from './routes/_authenticated/quotes.$quoteId'
import { Route as AuthenticatedProductsNewRouteImport } from './routes/_authenticated/products.new'
import { Route as AuthenticatedProductsProductIdRouteImport } from './routes/_authenticated/products.$productId'
import { Route as AuthenticatedOrdersOrderIdRouteImport } from './routes/_authenticated/orders.$orderId'
import { Route as AuthenticatedInvoicesInvoiceIdRouteImport } from './routes/_authenticated/invoices.$invoiceId'
import { Route as AuthenticatedGiftCardsGiftCardIdRouteImport } from './routes/_authenticated/gift-cards.$giftCardId'
import { Route as AuthenticatedCustomersCustomerIdRouteImport } from './routes/_authenticated/customers.$customerId'
import { Route as AuthenticatedCompaniesCompanyIdRouteImport } from './routes/_authenticated/companies.$companyId'
import { Route as AuthenticatedCollectionsNewRouteImport } from './routes/_authenticated/collections.new'
import { Route as AuthenticatedCollectionsCollectionIdRouteImport } from './routes/_authenticated/collections.$collectionId'
import { Route as AuthenticatedBlogsBlogIdRouteImport } from './routes/_authenticated/blogs.$blogId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedQuotesRoute = AuthenticatedQuotesRouteImport.update({
  id: '/quotes',
  path: '/quotes',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProductsRoute = AuthenticatedProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPriceListsRoute = AuthenticatedPriceListsRouteImport.update({
  id: '/price-lists',
  path: '/price-lists',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPagesRoute = AuthenticatedPagesRouteImport.update({
  id: '/pages',
  path: '/pages',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOrdersRoute = AuthenticatedOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMediaRoute = AuthenticatedMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedInvoicesRoute = AuthenticatedInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedInventoryRoute = AuthenticatedInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedGiftCardsRoute = AuthenticatedGiftCardsRouteImport.update({
  id: '/gift-cards',
  path: '/gift-cards',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDiscountsRoute = AuthenticatedDiscountsRouteImport.update({
  id: '/discounts',
  path: '/discounts',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCustomersRoute = AuthenticatedCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCompaniesRoute = AuthenticatedCompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCollectionsRoute =
  AuthenticatedCollectionsRouteImport.update({
    id: '/collections',
    path: '/collections',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedBlogsRoute = AuthenticatedBlogsRouteImport.update({
  id: '/blogs',
  path: '/blogs',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProductsIndexRoute =
  AuthenticatedProductsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedProductsRoute,
  } as any)
const AuthenticatedSettingsShippingRoute =
  AuthenticatedSettingsShippingRouteImport.update({
    id: '/settings/shipping',
    path: '/settings/shipping',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsPermissionsRoute =
  AuthenticatedSettingsPermissionsRouteImport.update({
    id: '/settings/permissions',
    path: '/settings/permissions',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsLocationsRoute =
  AuthenticatedSettingsLocationsRouteImport.update({
    id: '/settings/locations',
    path: '/settings/locations',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedQuotesQuoteIdRoute =
  AuthenticatedQuotesQuoteIdRouteImport.update({
    id: '/$quoteId',
    path: '/$quoteId',
    getParentRoute: () => AuthenticatedQuotesRoute,
  } as any)
const AuthenticatedProductsNewRoute =
  AuthenticatedProductsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedProductsRoute,
  } as any)
const AuthenticatedProductsProductIdRoute =
  AuthenticatedProductsProductIdRouteImport.update({
    id: '/$productId',
    path: '/$productId',
    getParentRoute: () => AuthenticatedProductsRoute,
  } as any)
const AuthenticatedOrdersOrderIdRoute =
  AuthenticatedOrdersOrderIdRouteImport.update({
    id: '/$orderId',
    path: '/$orderId',
    getParentRoute: () => AuthenticatedOrdersRoute,
  } as any)
const AuthenticatedInvoicesInvoiceIdRoute =
  AuthenticatedInvoicesInvoiceIdRouteImport.update({
    id: '/$invoiceId',
    path: '/$invoiceId',
    getParentRoute: () => AuthenticatedInvoicesRoute,
  } as any)
const AuthenticatedGiftCardsGiftCardIdRoute =
  AuthenticatedGiftCardsGiftCardIdRouteImport.update({
    id: '/$giftCardId',
    path: '/$giftCardId',
    getParentRoute: () => AuthenticatedGiftCardsRoute,
  } as any)
const AuthenticatedCustomersCustomerIdRoute =
  AuthenticatedCustomersCustomerIdRouteImport.update({
    id: '/$customerId',
    path: '/$customerId',
    getParentRoute: () => AuthenticatedCustomersRoute,
  } as any)
const AuthenticatedCompaniesCompanyIdRoute =
  AuthenticatedCompaniesCompanyIdRouteImport.update({
    id: '/$companyId',
    path: '/$companyId',
    getParentRoute: () => AuthenticatedCompaniesRoute,
  } as any)
const AuthenticatedCollectionsNewRoute =
  AuthenticatedCollectionsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedCollectionsRoute,
  } as any)
const AuthenticatedCollectionsCollectionIdRoute =
  AuthenticatedCollectionsCollectionIdRouteImport.update({
    id: '/$collectionId',
    path: '/$collectionId',
    getParentRoute: () => AuthenticatedCollectionsRoute,
  } as any)
const AuthenticatedBlogsBlogIdRoute =
  AuthenticatedBlogsBlogIdRouteImport.update({
    id: '/$blogId',
    path: '/$blogId',
    getParentRoute: () => AuthenticatedBlogsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/blogs': typeof AuthenticatedBlogsRouteWithChildren
  '/collections': typeof AuthenticatedCollectionsRouteWithChildren
  '/companies': typeof AuthenticatedCompaniesRouteWithChildren
  '/customers': typeof AuthenticatedCustomersRouteWithChildren
  '/discounts': typeof AuthenticatedDiscountsRoute
  '/gift-cards': typeof AuthenticatedGiftCardsRouteWithChildren
  '/inventory': typeof AuthenticatedInventoryRoute
  '/invoices': typeof AuthenticatedInvoicesRouteWithChildren
  '/media': typeof AuthenticatedMediaRoute
  '/orders': typeof AuthenticatedOrdersRouteWithChildren
  '/pages': typeof AuthenticatedPagesRoute
  '/price-lists': typeof AuthenticatedPriceListsRoute
  '/products': typeof AuthenticatedProductsRouteWithChildren
  '/quotes': typeof AuthenticatedQuotesRouteWithChildren
  '/blogs/$blogId': typeof AuthenticatedBlogsBlogIdRoute
  '/collections/$collectionId': typeof AuthenticatedCollectionsCollectionIdRoute
  '/collections/new': typeof AuthenticatedCollectionsNewRoute
  '/companies/$companyId': typeof AuthenticatedCompaniesCompanyIdRoute
  '/customers/$customerId': typeof AuthenticatedCustomersCustomerIdRoute
  '/gift-cards/$giftCardId': typeof AuthenticatedGiftCardsGiftCardIdRoute
  '/invoices/$invoiceId': typeof AuthenticatedInvoicesInvoiceIdRoute
  '/orders/$orderId': typeof AuthenticatedOrdersOrderIdRoute
  '/products/$productId': typeof AuthenticatedProductsProductIdRoute
  '/products/new': typeof AuthenticatedProductsNewRoute
  '/quotes/$quoteId': typeof AuthenticatedQuotesQuoteIdRoute
  '/settings/locations': typeof AuthenticatedSettingsLocationsRoute
  '/settings/permissions': typeof AuthenticatedSettingsPermissionsRoute
  '/settings/shipping': typeof AuthenticatedSettingsShippingRoute
  '/products/': typeof AuthenticatedProductsIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/blogs': typeof AuthenticatedBlogsRouteWithChildren
  '/collections': typeof AuthenticatedCollectionsRouteWithChildren
  '/companies': typeof AuthenticatedCompaniesRouteWithChildren
  '/customers': typeof AuthenticatedCustomersRouteWithChildren
  '/discounts': typeof AuthenticatedDiscountsRoute
  '/gift-cards': typeof AuthenticatedGiftCardsRouteWithChildren
  '/inventory': typeof AuthenticatedInventoryRoute
  '/invoices': typeof AuthenticatedInvoicesRouteWithChildren
  '/media': typeof AuthenticatedMediaRoute
  '/orders': typeof AuthenticatedOrdersRouteWithChildren
  '/pages': typeof AuthenticatedPagesRoute
  '/price-lists': typeof AuthenticatedPriceListsRoute
  '/quotes': typeof AuthenticatedQuotesRouteWithChildren
  '/': typeof AuthenticatedIndexRoute
  '/blogs/$blogId': typeof AuthenticatedBlogsBlogIdRoute
  '/collections/$collectionId': typeof AuthenticatedCollectionsCollectionIdRoute
  '/collections/new': typeof AuthenticatedCollectionsNewRoute
  '/companies/$companyId': typeof AuthenticatedCompaniesCompanyIdRoute
  '/customers/$customerId': typeof AuthenticatedCustomersCustomerIdRoute
  '/gift-cards/$giftCardId': typeof AuthenticatedGiftCardsGiftCardIdRoute
  '/invoices/$invoiceId': typeof AuthenticatedInvoicesInvoiceIdRoute
  '/orders/$orderId': typeof AuthenticatedOrdersOrderIdRoute
  '/products/$productId': typeof AuthenticatedProductsProductIdRoute
  '/products/new': typeof AuthenticatedProductsNewRoute
  '/quotes/$quoteId': typeof AuthenticatedQuotesQuoteIdRoute
  '/settings/locations': typeof AuthenticatedSettingsLocationsRoute
  '/settings/permissions': typeof AuthenticatedSettingsPermissionsRoute
  '/settings/shipping': typeof AuthenticatedSettingsShippingRoute
  '/products': typeof AuthenticatedProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/blogs': typeof AuthenticatedBlogsRouteWithChildren
  '/_authenticated/collections': typeof AuthenticatedCollectionsRouteWithChildren
  '/_authenticated/companies': typeof AuthenticatedCompaniesRouteWithChildren
  '/_authenticated/customers': typeof AuthenticatedCustomersRouteWithChildren
  '/_authenticated/discounts': typeof AuthenticatedDiscountsRoute
  '/_authenticated/gift-cards': typeof AuthenticatedGiftCardsRouteWithChildren
  '/_authenticated/inventory': typeof AuthenticatedInventoryRoute
  '/_authenticated/invoices': typeof AuthenticatedInvoicesRouteWithChildren
  '/_authenticated/media': typeof AuthenticatedMediaRoute
  '/_authenticated/orders': typeof AuthenticatedOrdersRouteWithChildren
  '/_authenticated/pages': typeof AuthenticatedPagesRoute
  '/_authenticated/price-lists': typeof AuthenticatedPriceListsRoute
  '/_authenticated/products': typeof AuthenticatedProductsRouteWithChildren
  '/_authenticated/quotes': typeof AuthenticatedQuotesRouteWithChildren
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/blogs/$blogId': typeof AuthenticatedBlogsBlogIdRoute
  '/_authenticated/collections/$collectionId': typeof AuthenticatedCollectionsCollectionIdRoute
  '/_authenticated/collections/new': typeof AuthenticatedCollectionsNewRoute
  '/_authenticated/companies/$companyId': typeof AuthenticatedCompaniesCompanyIdRoute
  '/_authenticated/customers/$customerId': typeof AuthenticatedCustomersCustomerIdRoute
  '/_authenticated/gift-cards/$giftCardId': typeof AuthenticatedGiftCardsGiftCardIdRoute
  '/_authenticated/invoices/$invoiceId': typeof AuthenticatedInvoicesInvoiceIdRoute
  '/_authenticated/orders/$orderId': typeof AuthenticatedOrdersOrderIdRoute
  '/_authenticated/products/$productId': typeof AuthenticatedProductsProductIdRoute
  '/_authenticated/products/new': typeof AuthenticatedProductsNewRoute
  '/_authenticated/quotes/$quoteId': typeof AuthenticatedQuotesQuoteIdRoute
  '/_authenticated/settings/locations': typeof AuthenticatedSettingsLocationsRoute
  '/_authenticated/settings/permissions': typeof AuthenticatedSettingsPermissionsRoute
  '/_authenticated/settings/shipping': typeof AuthenticatedSettingsShippingRoute
  '/_authenticated/products/': typeof AuthenticatedProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/blogs'
    | '/collections'
    | '/companies'
    | '/customers'
    | '/discounts'
    | '/gift-cards'
    | '/inventory'
    | '/invoices'
    | '/media'
    | '/orders'
    | '/pages'
    | '/price-lists'
    | '/products'
    | '/quotes'
    | '/blogs/$blogId'
    | '/collections/$collectionId'
    | '/collections/new'
    | '/companies/$companyId'
    | '/customers/$customerId'
    | '/gift-cards/$giftCardId'
    | '/invoices/$invoiceId'
    | '/orders/$orderId'
    | '/products/$productId'
    | '/products/new'
    | '/quotes/$quoteId'
    | '/settings/locations'
    | '/settings/permissions'
    | '/settings/shipping'
    | '/products/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/blogs'
    | '/collections'
    | '/companies'
    | '/customers'
    | '/discounts'
    | '/gift-cards'
    | '/inventory'
    | '/invoices'
    | '/media'
    | '/orders'
    | '/pages'
    | '/price-lists'
    | '/quotes'
    | '/'
    | '/blogs/$blogId'
    | '/collections/$collectionId'
    | '/collections/new'
    | '/companies/$companyId'
    | '/customers/$customerId'
    | '/gift-cards/$giftCardId'
    | '/invoices/$invoiceId'
    | '/orders/$orderId'
    | '/products/$productId'
    | '/products/new'
    | '/quotes/$quoteId'
    | '/settings/locations'
    | '/settings/permissions'
    | '/settings/shipping'
    | '/products'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/blogs'
    | '/_authenticated/collections'
    | '/_authenticated/companies'
    | '/_authenticated/customers'
    | '/_authenticated/discounts'
    | '/_authenticated/gift-cards'
    | '/_authenticated/inventory'
    | '/_authenticated/invoices'
    | '/_authenticated/media'
    | '/_authenticated/orders'
    | '/_authenticated/pages'
    | '/_authenticated/price-lists'
    | '/_authenticated/products'
    | '/_authenticated/quotes'
    | '/_authenticated/'
    | '/_authenticated/blogs/$blogId'
    | '/_authenticated/collections/$collectionId'
    | '/_authenticated/collections/new'
    | '/_authenticated/companies/$companyId'
    | '/_authenticated/customers/$customerId'
    | '/_authenticated/gift-cards/$giftCardId'
    | '/_authenticated/invoices/$invoiceId'
    | '/_authenticated/orders/$orderId'
    | '/_authenticated/products/$productId'
    | '/_authenticated/products/new'
    | '/_authenticated/quotes/$quoteId'
    | '/_authenticated/settings/locations'
    | '/_authenticated/settings/permissions'
    | '/_authenticated/settings/shipping'
    | '/_authenticated/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/quotes': {
      id: '/_authenticated/quotes'
      path: '/quotes'
      fullPath: '/quotes'
      preLoaderRoute: typeof AuthenticatedQuotesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/products': {
      id: '/_authenticated/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof AuthenticatedProductsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/price-lists': {
      id: '/_authenticated/price-lists'
      path: '/price-lists'
      fullPath: '/price-lists'
      preLoaderRoute: typeof AuthenticatedPriceListsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pages': {
      id: '/_authenticated/pages'
      path: '/pages'
      fullPath: '/pages'
      preLoaderRoute: typeof AuthenticatedPagesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/orders': {
      id: '/_authenticated/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof AuthenticatedOrdersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/media': {
      id: '/_authenticated/media'
      path: '/media'
      fullPath: '/media'
      preLoaderRoute: typeof AuthenticatedMediaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/invoices': {
      id: '/_authenticated/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof AuthenticatedInvoicesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inventory': {
      id: '/_authenticated/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AuthenticatedInventoryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/gift-cards': {
      id: '/_authenticated/gift-cards'
      path: '/gift-cards'
      fullPath: '/gift-cards'
      preLoaderRoute: typeof AuthenticatedGiftCardsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/discounts': {
      id: '/_authenticated/discounts'
      path: '/discounts'
      fullPath: '/discounts'
      preLoaderRoute: typeof AuthenticatedDiscountsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/customers': {
      id: '/_authenticated/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AuthenticatedCustomersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/companies': {
      id: '/_authenticated/companies'
      path: '/companies'
      fullPath: '/companies'
      preLoaderRoute: typeof AuthenticatedCompaniesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/collections': {
      id: '/_authenticated/collections'
      path: '/collections'
      fullPath: '/collections'
      preLoaderRoute: typeof AuthenticatedCollectionsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/blogs': {
      id: '/_authenticated/blogs'
      path: '/blogs'
      fullPath: '/blogs'
      preLoaderRoute: typeof AuthenticatedBlogsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/products/': {
      id: '/_authenticated/products/'
      path: '/'
      fullPath: '/products/'
      preLoaderRoute: typeof AuthenticatedProductsIndexRouteImport
      parentRoute: typeof AuthenticatedProductsRoute
    }
    '/_authenticated/settings/shipping': {
      id: '/_authenticated/settings/shipping'
      path: '/settings/shipping'
      fullPath: '/settings/shipping'
      preLoaderRoute: typeof AuthenticatedSettingsShippingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/permissions': {
      id: '/_authenticated/settings/permissions'
      path: '/settings/permissions'
      fullPath: '/settings/permissions'
      preLoaderRoute: typeof AuthenticatedSettingsPermissionsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/locations': {
      id: '/_authenticated/settings/locations'
      path: '/settings/locations'
      fullPath: '/settings/locations'
      preLoaderRoute: typeof AuthenticatedSettingsLocationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/quotes/$quoteId': {
      id: '/_authenticated/quotes/$quoteId'
      path: '/$quoteId'
      fullPath: '/quotes/$quoteId'
      preLoaderRoute: typeof AuthenticatedQuotesQuoteIdRouteImport
      parentRoute: typeof AuthenticatedQuotesRoute
    }
    '/_authenticated/products/new': {
      id: '/_authenticated/products/new'
      path: '/new'
      fullPath: '/products/new'
      preLoaderRoute: typeof AuthenticatedProductsNewRouteImport
      parentRoute: typeof AuthenticatedProductsRoute
    }
    '/_authenticated/products/$productId': {
      id: '/_authenticated/products/$productId'
      path: '/$productId'
      fullPath: '/products/$productId'
      preLoaderRoute: typeof AuthenticatedProductsProductIdRouteImport
      parentRoute: typeof AuthenticatedProductsRoute
    }
    '/_authenticated/orders/$orderId': {
      id: '/_authenticated/orders/$orderId'
      path: '/$orderId'
      fullPath: '/orders/$orderId'
      preLoaderRoute: typeof AuthenticatedOrdersOrderIdRouteImport
      parentRoute: typeof AuthenticatedOrdersRoute
    }
    '/_authenticated/invoices/$invoiceId': {
      id: '/_authenticated/invoices/$invoiceId'
      path: '/$invoiceId'
      fullPath: '/invoices/$invoiceId'
      preLoaderRoute: typeof AuthenticatedInvoicesInvoiceIdRouteImport
      parentRoute: typeof AuthenticatedInvoicesRoute
    }
    '/_authenticated/gift-cards/$giftCardId': {
      id: '/_authenticated/gift-cards/$giftCardId'
      path: '/$giftCardId'
      fullPath: '/gift-cards/$giftCardId'
      preLoaderRoute: typeof AuthenticatedGiftCardsGiftCardIdRouteImport
      parentRoute: typeof AuthenticatedGiftCardsRoute
    }
    '/_authenticated/customers/$customerId': {
      id: '/_authenticated/customers/$customerId'
      path: '/$customerId'
      fullPath: '/customers/$customerId'
      preLoaderRoute: typeof AuthenticatedCustomersCustomerIdRouteImport
      parentRoute: typeof AuthenticatedCustomersRoute
    }
    '/_authenticated/companies/$companyId': {
      id: '/_authenticated/companies/$companyId'
      path: '/$companyId'
      fullPath: '/companies/$companyId'
      preLoaderRoute: typeof AuthenticatedCompaniesCompanyIdRouteImport
      parentRoute: typeof AuthenticatedCompaniesRoute
    }
    '/_authenticated/collections/new': {
      id: '/_authenticated/collections/new'
      path: '/new'
      fullPath: '/collections/new'
      preLoaderRoute: typeof AuthenticatedCollectionsNewRouteImport
      parentRoute: typeof AuthenticatedCollectionsRoute
    }
    '/_authenticated/collections/$collectionId': {
      id: '/_authenticated/collections/$collectionId'
      path: '/$collectionId'
      fullPath: '/collections/$collectionId'
      preLoaderRoute: typeof AuthenticatedCollectionsCollectionIdRouteImport
      parentRoute: typeof AuthenticatedCollectionsRoute
    }
    '/_authenticated/blogs/$blogId': {
      id: '/_authenticated/blogs/$blogId'
      path: '/$blogId'
      fullPath: '/blogs/$blogId'
      preLoaderRoute: typeof AuthenticatedBlogsBlogIdRouteImport
      parentRoute: typeof AuthenticatedBlogsRoute
    }
  }
}

interface AuthenticatedBlogsRouteChildren {
  AuthenticatedBlogsBlogIdRoute: typeof AuthenticatedBlogsBlogIdRoute
}

const AuthenticatedBlogsRouteChildren: AuthenticatedBlogsRouteChildren = {
  AuthenticatedBlogsBlogIdRoute: AuthenticatedBlogsBlogIdRoute,
}

const AuthenticatedBlogsRouteWithChildren =
  AuthenticatedBlogsRoute._addFileChildren(AuthenticatedBlogsRouteChildren)

interface AuthenticatedCollectionsRouteChildren {
  AuthenticatedCollectionsCollectionIdRoute: typeof AuthenticatedCollectionsCollectionIdRoute
  AuthenticatedCollectionsNewRoute: typeof AuthenticatedCollectionsNewRoute
}

const AuthenticatedCollectionsRouteChildren: AuthenticatedCollectionsRouteChildren =
  {
    AuthenticatedCollectionsCollectionIdRoute:
      AuthenticatedCollectionsCollectionIdRoute,
    AuthenticatedCollectionsNewRoute: AuthenticatedCollectionsNewRoute,
  }

const AuthenticatedCollectionsRouteWithChildren =
  AuthenticatedCollectionsRoute._addFileChildren(
    AuthenticatedCollectionsRouteChildren,
  )

interface AuthenticatedCompaniesRouteChildren {
  AuthenticatedCompaniesCompanyIdRoute: typeof AuthenticatedCompaniesCompanyIdRoute
}

const AuthenticatedCompaniesRouteChildren: AuthenticatedCompaniesRouteChildren =
  {
    AuthenticatedCompaniesCompanyIdRoute: AuthenticatedCompaniesCompanyIdRoute,
  }

const AuthenticatedCompaniesRouteWithChildren =
  AuthenticatedCompaniesRoute._addFileChildren(
    AuthenticatedCompaniesRouteChildren,
  )

interface AuthenticatedCustomersRouteChildren {
  AuthenticatedCustomersCustomerIdRoute: typeof AuthenticatedCustomersCustomerIdRoute
}

const AuthenticatedCustomersRouteChildren: AuthenticatedCustomersRouteChildren =
  {
    AuthenticatedCustomersCustomerIdRoute:
      AuthenticatedCustomersCustomerIdRoute,
  }

const AuthenticatedCustomersRouteWithChildren =
  AuthenticatedCustomersRoute._addFileChildren(
    AuthenticatedCustomersRouteChildren,
  )

interface AuthenticatedGiftCardsRouteChildren {
  AuthenticatedGiftCardsGiftCardIdRoute: typeof AuthenticatedGiftCardsGiftCardIdRoute
}

const AuthenticatedGiftCardsRouteChildren: AuthenticatedGiftCardsRouteChildren =
  {
    AuthenticatedGiftCardsGiftCardIdRoute:
      AuthenticatedGiftCardsGiftCardIdRoute,
  }

const AuthenticatedGiftCardsRouteWithChildren =
  AuthenticatedGiftCardsRoute._addFileChildren(
    AuthenticatedGiftCardsRouteChildren,
  )

interface AuthenticatedInvoicesRouteChildren {
  AuthenticatedInvoicesInvoiceIdRoute: typeof AuthenticatedInvoicesInvoiceIdRoute
}

const AuthenticatedInvoicesRouteChildren: AuthenticatedInvoicesRouteChildren = {
  AuthenticatedInvoicesInvoiceIdRoute: AuthenticatedInvoicesInvoiceIdRoute,
}

const AuthenticatedInvoicesRouteWithChildren =
  AuthenticatedInvoicesRoute._addFileChildren(
    AuthenticatedInvoicesRouteChildren,
  )

interface AuthenticatedOrdersRouteChildren {
  AuthenticatedOrdersOrderIdRoute: typeof AuthenticatedOrdersOrderIdRoute
}

const AuthenticatedOrdersRouteChildren: AuthenticatedOrdersRouteChildren = {
  AuthenticatedOrdersOrderIdRoute: AuthenticatedOrdersOrderIdRoute,
}

const AuthenticatedOrdersRouteWithChildren =
  AuthenticatedOrdersRoute._addFileChildren(AuthenticatedOrdersRouteChildren)

interface AuthenticatedProductsRouteChildren {
  AuthenticatedProductsProductIdRoute: typeof AuthenticatedProductsProductIdRoute
  AuthenticatedProductsNewRoute: typeof AuthenticatedProductsNewRoute
  AuthenticatedProductsIndexRoute: typeof AuthenticatedProductsIndexRoute
}

const AuthenticatedProductsRouteChildren: AuthenticatedProductsRouteChildren = {
  AuthenticatedProductsProductIdRoute: AuthenticatedProductsProductIdRoute,
  AuthenticatedProductsNewRoute: AuthenticatedProductsNewRoute,
  AuthenticatedProductsIndexRoute: AuthenticatedProductsIndexRoute,
}

const AuthenticatedProductsRouteWithChildren =
  AuthenticatedProductsRoute._addFileChildren(
    AuthenticatedProductsRouteChildren,
  )

interface AuthenticatedQuotesRouteChildren {
  AuthenticatedQuotesQuoteIdRoute: typeof AuthenticatedQuotesQuoteIdRoute
}

const AuthenticatedQuotesRouteChildren: AuthenticatedQuotesRouteChildren = {
  AuthenticatedQuotesQuoteIdRoute: AuthenticatedQuotesQuoteIdRoute,
}

const AuthenticatedQuotesRouteWithChildren =
  AuthenticatedQuotesRoute._addFileChildren(AuthenticatedQuotesRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedBlogsRoute: typeof AuthenticatedBlogsRouteWithChildren
  AuthenticatedCollectionsRoute: typeof AuthenticatedCollectionsRouteWithChildren
  AuthenticatedCompaniesRoute: typeof AuthenticatedCompaniesRouteWithChildren
  AuthenticatedCustomersRoute: typeof AuthenticatedCustomersRouteWithChildren
  AuthenticatedDiscountsRoute: typeof AuthenticatedDiscountsRoute
  AuthenticatedGiftCardsRoute: typeof AuthenticatedGiftCardsRouteWithChildren
  AuthenticatedInventoryRoute: typeof AuthenticatedInventoryRoute
  AuthenticatedInvoicesRoute: typeof AuthenticatedInvoicesRouteWithChildren
  AuthenticatedMediaRoute: typeof AuthenticatedMediaRoute
  AuthenticatedOrdersRoute: typeof AuthenticatedOrdersRouteWithChildren
  AuthenticatedPagesRoute: typeof AuthenticatedPagesRoute
  AuthenticatedPriceListsRoute: typeof AuthenticatedPriceListsRoute
  AuthenticatedProductsRoute: typeof AuthenticatedProductsRouteWithChildren
  AuthenticatedQuotesRoute: typeof AuthenticatedQuotesRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedSettingsLocationsRoute: typeof AuthenticatedSettingsLocationsRoute
  AuthenticatedSettingsPermissionsRoute: typeof AuthenticatedSettingsPermissionsRoute
  AuthenticatedSettingsShippingRoute: typeof AuthenticatedSettingsShippingRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedBlogsRoute: AuthenticatedBlogsRouteWithChildren,
  AuthenticatedCollectionsRoute: AuthenticatedCollectionsRouteWithChildren,
  AuthenticatedCompaniesRoute: AuthenticatedCompaniesRouteWithChildren,
  AuthenticatedCustomersRoute: AuthenticatedCustomersRouteWithChildren,
  AuthenticatedDiscountsRoute: AuthenticatedDiscountsRoute,
  AuthenticatedGiftCardsRoute: AuthenticatedGiftCardsRouteWithChildren,
  AuthenticatedInventoryRoute: AuthenticatedInventoryRoute,
  AuthenticatedInvoicesRoute: AuthenticatedInvoicesRouteWithChildren,
  AuthenticatedMediaRoute: AuthenticatedMediaRoute,
  AuthenticatedOrdersRoute: AuthenticatedOrdersRouteWithChildren,
  AuthenticatedPagesRoute: AuthenticatedPagesRoute,
  AuthenticatedPriceListsRoute: AuthenticatedPriceListsRoute,
  AuthenticatedProductsRoute: AuthenticatedProductsRouteWithChildren,
  AuthenticatedQuotesRoute: AuthenticatedQuotesRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedSettingsLocationsRoute: AuthenticatedSettingsLocationsRoute,
  AuthenticatedSettingsPermissionsRoute: AuthenticatedSettingsPermissionsRoute,
  AuthenticatedSettingsShippingRoute: AuthenticatedSettingsShippingRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
